version: '3.9'

services:

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PWD
    volumes:
      - mysql:/var/lib/mysql
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PWD

  # backend:
  #   links:
  #     - mysql
  #   depends_on:
  #     - mysql
  #   container_name: backend
  #   ports:
  #     - '8000:8000'
  #   build:
  #     context: .
  #     dockerfile: ./apps/backend/Dockerfile
  #   volumes:
  #     - ./apps/backend:/app/apps/backend
  #     - /app/apps/backend/node_modules
    # command: yarn start:docker

volumes:
  mysql: